In [5]:
!python main.py \
    feature_type=r21d \
    device="cuda:0" \
    video_paths="[./sample/v_ZNVhz7ctTq0.mp4, ./sample/v_GGSY1Qvo990.mp4]"

feature_type: r21d
model_name: r2plus1d_18_16_kinetics
stack_size: null
step_size: null
extraction_fps: null
device: cuda:0
on_extraction: print
output_path: ./output\r21d\r2plus1d_18_16_kinetics
tmp_path: ./tmp\r21d\r2plus1d_18_16_kinetics
keep_tmp_files: false
show_pred: false
config: null
video_paths:
- ./sample/v_ZNVhz7ctTq0.mp4
- ./sample/v_GGSY1Qvo990.mp4
file_with_video_paths: null

Device: cuda:0
The number of specified videos: 2
r21d
[[0.42217487 1.17241478 0.40108061 ... 0.66955972 0.06912975 1.18544972]
 [0.52834147 0.86625701 0.48407453 ... 0.87204832 0.06442701 1.27014625]
 [0.45514068 1.24139607 0.28752321 ... 1.19740975 0.04061373 1.18316901]
 ...
 [0.36856094 0.72175956 0.42999309 ... 1.50359106 0.64502478 0.92296231]
 [0.36783111 0.57700574 0.39525458 ... 1.56007409 0.47313643 0.55631542]
 [0.26918149 0.62723058 0.15492553 ... 1.86682606 0.16253105 0.45002201]]
max: 5.85783100; mean: 0.97720358; min: 0.00000000

r21d
[[0.29413179 0.61645156 0.03124532 ... 0.46446839 0.


100%|██████████| 2/2 [00:03<00:00,  1.76s/it]


In [9]:
!python main.py \
    feature_type=i3d \
    device="cuda:0" \
    video_paths="[../PreProcess/ori_Training/C_3_12_1_BU_SMB_08-28_16-25-27_CC_RGB_DF2_M1.mp4]" \
    on_extraction="save_numpy" \
    output_path="./output/i3d/kinetics"

feature_type: i3d
stack_size: 64
step_size: 64
streams: null
flow_type: raft
extraction_fps: null
device: cuda:0
on_extraction: save_numpy
output_path: ./output/i3d/kinetics\i3d
tmp_path: ./tmp\i3d
keep_tmp_files: false
show_pred: false
config: null
video_paths:
- ../PreProcess/ori_Training/C_3_12_1_BU_SMB_08-28_16-25-27_CC_RGB_DF2_M1.mp4
file_with_video_paths: null

Saving features to ./output/i3d/kinetics\i3d
Device: cuda:0
The number of specified videos: 1



100%|██████████| 1/1 [00:04<00:00,  4.73s/it]
